# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weibull_optimize <- function(X, Z, tt0, tt, d, pfixed, w, offset, print = TRUE, init_theta, method = "BFGS", control = NULL) {
    .Call(`_rstreg_weibull_optimize`, X, Z, tt0, tt, d, pfixed, w, offset, print, init_theta, method, control)
}

weibull_gr <- function(theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    .Call(`_rstreg_weibull_gr`, theta, X, Z, tt0, tt, d, pfixed, w, offset)
}

weibull_hess <- function(theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    .Call(`_rstreg_weibull_hess`, theta, X, Z, tt0, tt, d, pfixed, w, offset)
}

weibull_inplace <- function(llval, grObsval, grval, hessval, theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    invisible(.Call(`_rstreg_weibull_inplace`, llval, grObsval, grval, hessval, theta, X, Z, tt0, tt, d, pfixed, w, offset))
}

weibull_ll <- function(theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    .Call(`_rstreg_weibull_ll`, theta, X, Z, tt0, tt, d, pfixed, w, offset)
}

weibull_max_nr <- function(maxiter, X, Z, tt0, tt, d, pfixed, wt, offset, theta, eps, tol) {
    .Call(`_rstreg_weibull_max_nr`, maxiter, X, Z, tt0, tt, d, pfixed, wt, offset, theta, eps, tol)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_rstreg_RcppExport_registerCCallable`)
})
