# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weibull_gr <- function(theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    .Call(`_rstreg_weibull_gr`, theta, X, Z, tt0, tt, d, pfixed, w, offset)
}

weibull_hess <- function(theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    .Call(`_rstreg_weibull_hess`, theta, X, Z, tt0, tt, d, pfixed, w, offset)
}

weibull_ll <- function(theta, X, Z, tt0, tt, d, pfixed, w, offset) {
    .Call(`_rstreg_weibull_ll`, theta, X, Z, tt0, tt, d, pfixed, w, offset)
}

